name: ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruby-qa:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: kaching
          POSTGRES_PASSWORD: kaching
          LC_ALL: C.UTF-8
          LANG: en_US.UTF-8
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RACK_ENV: test
      DATABASE_URL: localhost
      DATABASE_USER: kaching
      DATABASE_PASSWORD: kaching
      DATABASE_NAME_SHARED: kaching_development

    strategy:
      fail-fast: false
      matrix:
        ruby: ["ruby-3.2"]
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Creating shared database
        run: bundle exec rake db:shared:init

      - name: Creating base database
        run: bundle exec rake db:create

      - name: Migrating base database
        run: bundle exec rake db:migrate

      - name: Preparing database
        run: bundle exec rake db:test:prepare

      - name: Run tests
        run: bundle exec rake

      - name: Rubocop
        run: bundle exec rubocop
